# Generated by Django 4.2 on 2024-07-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_attack_pokemon_image_url_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='audio_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
