# Generated by Django 4.2 on 2024-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('level', models.IntegerField()),
                ('image_url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
