# Generated by Django 4.2 on 2024-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image_url',
            field=models.ImageField(default='', upload_to='trainers/'),
        ),
    ]
