# Generated by Django 4.2 on 2024-08-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_trainer_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_url',
            field=models.ImageField(default='', upload_to='pokemons/'),
        ),
    ]
