# Generated by Django 4.2 on 2024-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemon_trainer_alter_pokemon_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='audio_url',
            field=models.FileField(blank=True, default='', upload_to='pokemons/audio/'),
        ),
    ]
