# Generated by Django 4.2 on 2024-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='audio_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=100),
        ),
    ]
