# Generated by Django 4.2 on 2024-08-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_audio_url_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='audio_url',
            field=models.FileField(blank=True, default='', null=True, upload_to='audio/'),
        ),
    ]
